### ISSUE TITLE
Proposal:  Lock Meeting List to only Web Team Members

### ISSUE THREAD

**Issue by KrisRecoveryDharma** [RecoveryDharma/website#10]
I propose that we lock the meeting list so that only web team members may edit it.  Everyone else is view only. 

If the task of updating the list is too much for one person, then we can set up a system where either requests go to all of us, or maybe we alternate weeks, or something so that no one person is on-call all of the time. 

Thoughts? 

Kris

**Comment by nutjob4life** [comment]
Sounds reasonable to me @KrisRecoveryDharma.

@unity1979 is this something you can do?

**Comment by KrisRecoveryDharma** [comment]
Thank you for moving towards assignment.  This is a task that I can complete. I just wanted to make sure we are all in agreement. 

Kris

**Comment by KrisRecoveryDharma** [comment]
Sean - were you referring to the task of making the sheet private or the task of joining the team to monitor the list requests? 

One of the essential priorities I set for the new list and the new site was an action user feature with the meeting list so that groups could update their listing themselves. So, this will hopefully only be a process that is in place until November.

**Comment by unity1979** [comment]
I can do this.  One small change however--instead of locking meeting list to **"View Only"** mode, I might suggest:

**Proposal**: Change rights from "Editor" to "Comment Only" mode.  
**Reason**: 
1) Comment Only rights removes risks of deleting/destroying the spreadsheet.  
2) Reduces the effort required to update a meeting.  Commenters could simply leave a comment on a specific cell, telling us exactly what needs to be updated and what it needs to be updated to (instead of resubmitting an entire form, and forcing us to guess which meeting they are probably talking about that needs updating).  

See image for example. Let me know if this needs clarification.  

![image](https://user-images.githubusercontent.com/70724023/92296264-bd5bfd80-eee7-11ea-8444-b99a66032b83.png)

Here is a list of all individuals with EDITOR access to the unprotected sheets:

1. Angela Walker  walkeran(at)usc.edu
2. Bee Sloan  bsloan(at)pps.net
3. Ben Gabrielli  benmate(at)gmail.com
4. Chris Carter  cjcarter.uk(at)gmail.com
5. Craig Schorn  craigschorn(at)gmail.com
6. CS AW   faeriecritter(at)gmail.com
7. Dirk Wethington  dwethington(at)recoverydharma.org
8. Douglas Pearson  dbpearson67(at)gmail.com
9. Eastside Recovery Dharma   eastsiderecoverydharma(at)gmail.com
10. Flo Sheffield  flosheffield(at)gmail.com
11. Jean Tuller  jean(at)recoverydharma.org
12. Jed Reay  jedreay(at)gmail.com
13. Joel Osterman  joel.r.osterman(at)gmail.com
14. Johntony El Rey  jotofa(at)gmail.com
15. Kelly Anderson  kellyjeanslucky(at)gmail.com
16. Linda Brink  Hubbydogme(at)gmail.com
17. Lynda Stanford  eastmeetsweststemcells(at)gmail.com
18. Mary Kate Farley-Dimino  marykatefarley(at)gmail.com
19. Nicholas Hallam  recoverydharmabrighton(at)gmail.com
20. Nigel Eddies  aptracy(at)yahoo.com
21. Ojoku  ojoku1012(at)gmail.com
22. Paul Budd  paul(at)theunityagency.co.uk
23. Rachel Sobel  rsobel1969(at)gmail.com
24. Ryan K  justRyanOK(at)charter.net
25. Susan Wynne  susanwwynne(at)gmail.com
26. Wade Crawford  wade.f.crawford(at)gmail.com

**Comment by unity1979** [comment]
So for me to proceed: let me know if/when it's ok for me to:
1) Update all non-member access to **Comment Only** mode

Else please advise on how to proceed

**Comment by KrisRecoveryDharma** [comment]
HI Sean and Thom,

Thank your for your thoughts. Unfortunately, it does not appear that
commenting is an option with google sheets. It appears to be either "edit
or no." Thank you for the offer to take-on the ask.  Apparently I am not
yet feeling ready to delegate this task to others. I also want to make sure
we don't many any changes until after Craig checks in.

Thanks,

Kris

**Comment by unity1979** [comment]
By clicking the green [Share] button in the upper right corner, we can set permission levels, notice:
![image](https://user-images.githubusercontent.com/70724023/92304736-654be800-ef35-11ea-975c-b2dd2374ef8d.png)

**Comment by KrisRecoveryDharma** [comment]
I like the idea of making it Comment friendly.  I swear, it was not showing up last night when I looked!  Or maybe I had a blind spot.  That happens when I'm tired.  Same thing happens with my keys as they are sitting right in front of me. 

We could just mark the overall sharing level as  "Anyone with the link can comment."   Until or unless we get trouble with trolls, I would prefer that.  It means less day to day maintenance from us.

**Comment by KrisRecoveryDharma** [comment]
Craig has chimed in on slack that he agrees with this proposal.  

I need to add one more change:  I need to shift my google account from roehlkris@gmail.com to kris@recoverydharma.org. 

So, Editors include:
Craig Wilke - owner
Kris Roehing kris@recoverydharma.org
Sean Kelly - kelly@recoverydharma.org
A Thomas Tran - anthomas@gmail.com
Lacey Browne - lacey@recoverydharma.org

Should Thomas have a Recovery Dharma Email? Would you like a recovery dharma email?

**Comment by unity1979** [comment]
Updates have been made as follows: 

All permissions have been set to "Commentor"  except for:
Webteam members have been set to "Editor" (currently Craig, Kris, Lacey, Sean, Thomas)

Btw @KrisRecoveryDharma, consolidating email to go to thomas@recoverydharma.org would be useful moving forward. Thank you

**Comment by KrisRecoveryDharma** [comment]
Thank you Thomas for fixing the list! 

1. Request for Recovery Dharma email for Thom has been sent to RDG Secretary.  As soon as we get that, then we can update the list. 

2. The change to my email did not take, so I went in and made the switch to from my person email to my RD Email.

3. I changed the general permission to anyone with the link can comment.

**Comment by KrisRecoveryDharma** [comment]
Issue will close once Thom has received Recovery Dharma Email.

**Comment by unity1979** [comment]
![image](https://user-images.githubusercontent.com/70724023/93275841-dc258400-f772-11ea-818f-9db6d3f58ec8.png)

Verifying that I've received the Recovery Dharma email, thank you for your patience. 🙏
