### ISSUE TITLE
Pop up on home page - Go to the Sangha Summit

### ISSUE THREAD

**Issue by KrisRecoveryDharma** [RecoveryDharma/website#122]
We need a pop-up for the front page that says "Go to the Sangha Summit!

It needs to link to the 2022 sangha summit landing page.  https://recoverydharma.org/2022-sangha-summit/

Kris Roehling

**Comment by tom-raley** [comment]
Hey @KrisRecoveryDharma for this--do we want something similar to the pop up that was there when the site first launched? Or did you have something else in mind?

**Comment by tom-raley** [comment]
@KrisRecoveryDharma Looks like Divi Overlays is what was used to create the site launch one. They have a library of templates we can use, but you have to log in to Divi in order to access the templates. The only template we currently have available is the one used for site launch which covers the whole screen. So this might be a firespring thing where they would need to upload a different overlay template, or we need to explore other plugins that will allow us to do this.

**Comment by KrisRecoveryDharma** [comment]
That is fine, then.  Go ahead with the whe screen version

**Comment by tom-raley** [comment]
@KrisRecoveryDharma Ok, this is now live on the site. Let me know if the design looks ok. The entire page is a link except for the close button, as the current overlay module won't allow me to use hyperlinks except for to make the entire page a link basically. I also implemented a 7 day cookie after a user closes the overlay, so it won't keep bugging them every time they go to the site, but will give them a reminder every week essentially. We can change the expiration of this cookie if we want as well.

Let me know your thoughts!
