### ISSUE TITLE
Clarify difference between in person and online meeting list

### ISSUE THREAD

**Issue by KrisRecoveryDharma** [RecoveryDharma/website#13]
## 📕 Summary
Change existing content. 
Issue:  The links to the meeting list is unclear.  It looks as though the online meetings are a subset of the In Person Meeting.  Below are my suggestions. Let me know if you can think of a better solution. 

https://recoverydharma.org/meeting-list

Current: 
FIND A MEETING
Online Meetings
Follow any of the links below for meetings listed in a time zone near you:
In Person Meetings https://docs.google.com/spreadsheets/d/13sb_3p0pX-WLMnQP9kOszR1WE5LeeeamycD_carKn0g/edit#gid=1492891510
* Hawaii  https://docs.google.com/spreadsheets/d/13sb_3p0pX-WLMnQP9kOszR1WE5LeeeamycD_carKn0g/edit#gid=496973103

Change to:
FIND A MEETING

In Person Meetings 

Online Meetings
* Hawaii 

*********************************************
Also Change Menu:

Current: 
* In Person Meetings
* Hawaii

Change to:
* In Person Meetings
Online Meetings
* Hawaii

Thanks!

**Comment by nutjob4life** [comment]
The page at https://recoverydharma.org/meeting-list is updated.

The menu has also been updated, however because menus are "heavily cached" it may not show up right away for you.

For now, here's a screenshot of the new menu:
![Screen Shot 2020-09-14 at 11 16 37 AM](https://user-images.githubusercontent.com/814813/93111252-f7619800-f67b-11ea-8429-a3be7792eac3.png)

If this works out, go ahead and close this issue. If not, let me know what else you'd like to see in a comment below.

**Comment by KrisRecoveryDharma** [comment]
Looks great! 
Thank you!
Kris
