### ISSUE TITLE
Donation Page Broken

### ISSUE THREAD

**Issue by randallwesleyhall** [RecoveryDharma/website#188]
The Contribute page is broken. Not sure what is happening but cannot even see the PayPal link to donate.

https://recoverydharma.org/contribute/

**Comment by jerclarke** [comment]
Same bug as with the book page and others. 

Thoughts as a professional WP developer: 

The way it ultimately resolves when this happens -- we  wait a variable period of time then suddenly it's fixed -- implies that whatever the issue is, it's being exacerbated by some kind of caching system, where the bugged pageload is saved indefinitely and served over and over. Caching is used to speed up the site by saving a copy and serving it over and over rather than serving a fresh one each time, but a downside is that in situations like this, the broken one gets stuck in there.  

I looks like you're using https://www.fastly.com/, which I have no experience with, but which is probably the place where this could be addressed. If nothing else, there's probably a button somewhere on Fastly you could use to "flush the cache" and force a fresh copy to be loaded, which is what happens eventually otherwise. If you have a Fastly plugin running in WordPress, it's possible you also have a "Flush cache" button somewhere in /wp-admin/ that you could use. 

Finding that button and pushing it would be better than these Github tickets, though addressing the underlying issue so the pages aren't broken and don't get cached at all would be better.

**Comment by tom-raley** [comment]
I haven't been able to reproduce this issue intentionally and since it happens intermittently and we don't have access to the error logs (which I've asked for before :) ) from Firespring, I have no real way to troubleshoot this most of the time. Even if I were to go and disable each plugin individually to find the culprit, I have no way to intentionally reproduce and would just have to wait for it to happen again randomly while each plugin is inactive.

@jerclarke is right that clearing the cache would likely solve this issue in the short term when it happens, but beyond bugging firespring again about helping us fix this, I'm not really sure where to go with it. 

Open to suggestions or ideas or help on it, as I don't have much bandwidth right now. Closing for now as pages are functional. We can open another issue if someone has time/bandwidth to address it.
