### ISSUE TITLE
Add Categories to New Page

### ISSUE THREAD

**Issue by KrisRecoveryDharma** [RecoveryDharma/website#86]
This is a widget change, so I was not able to navigate it. 
Thank you for the quick updates on the Blog - now News section!
Here's what's next:  Adding categories to tag new articles. 

## 📕 Summary

Replace this with a brief description of the content you want to be changed. Make sure to check if this is
- [ ] new content  for https://recovery-dharma.flywheelsites.com/blog/

## 🔍 Details

Replace this with detailed information about the request. For new content, make sure to mention

I want to add two categories to the Side Bar.  Apparently, this is done on the widget page and the results are done here.  I want to add the following categories.  Following the alphabetical sort when they are displayed will be good. 

Personal Stories
Diversity and Accessibility
Refuge
Four Noble Truths
Eightfold Path
Sangha Spotlight
Practice
Getting Started

Thanks!

**Comment by tom-raley** [comment]
Hey @KrisRecoveryDharma, here is the current list of categories:

Bulletins
Community
Events
News
Organization
Practice
Teaching

I'm just confused on which ones from above we are adding and whether we should keep all the ones that are currently listed, since there appears to be more than 2 that are being added. Let me know if we should combine both lists or add/remove any of the current ones.
